#!/bin/bash
#########################################
# Script Name: 00_Setup.sh
# Purpose: Create the required folder structure
#          for project
#########################################

# --- Create top-level directories ---
mkdir results          # Store analysis results
mkdir scripts          # Store analysis scripts

# --- Create subdirectories inside scripts ---
cd scripts
mkdir output           # Output files generated by scripts
cd ../

# --- Create data directory for all project data ---
mkdir data

# --- Create subdirectories for raw and processed data ---
cd data
mkdir raw              # Raw data from sequencing facility
mkdir processed        # Processed data after QC/mapping

# --- Create subdirectories inside processed ---
cd processed
mkdir bam              # Aligned sequencing data (.bam files)
mkdir wgs_metrics      # Whole genome sequencing quality metrics
mkdir bed              # Genomic intervals (.bed files)
mkdir quality_cont     # Quality control reports
mkdir trimmed          # Trimmed FASTQ files
mkdir samtools_stat    # Statistics from samtools
mkdir txt              # Tab-delimited or text files
mkdir coverage         # Coverage analysis results
mkdir insert_size_metrics # Insert size metrics from sequencing
mkdir preseq           # Library complexity estimation
cd ../../
